### ISSUE TITLE
Unable to launch Android emulator on macOS-latest agent

### ISSUE THREAD

**Issue by Avi29071991** [MicrosoftDocs/pipelines-android#15]
I am having an existing build pipeline for creating debug Android builds once the Integration tests and unit tests are successful. This pipeline was running without any issues till 26th September 2024. After 26th of September the build pipeline is unable to start the Android emulator for running the integration tests thereby failing my pipeline job. The code which I use for Installing android sdk image and starting the emulator is as shown below:
```
  - bash: |
      echo "y" | $ANDROID_HOME/tools/bin/sdkmanager --install 'system-images;android-30;default;x86_64'
      echo "y" | $ANDROID_HOME/tools/bin/sdkmanager --licenses
    displayName: 'Download and install emulator image'
    condition: and(eq(variables['Build.SourceBranchName'], '${{ parameters.branchName }}'), eq(variables['Build.Reason'], '${{ parameters.buildReason }}'))

  - bash: |
      echo "no" | $ANDROID_HOME/tools/bin/avdmanager create avd -n android_emulator -d pixel --package 'system-images;android-30;default;x86_64' --force
      $ANDROID_HOME/emulator/emulator -list-avds
      emulator_config=~/.android/avd/android_emulator.avd/config.ini
      # The following madness is to support empty OR populated config.ini files,
      # the state of which is dependant on the version of the emulator used (which we don't control),
      # so let's be defensive to be safe.
      # Replace existing config (NOTE we're on MacOS so sed works differently!)
      sed -i .bak 's/hw.lcd.density=.*/hw.lcd.density=420/' "$emulator_config"
      sed -i .bak 's/hw.lcd.height=.*/hw.lcd.height=1920/' "$emulator_config"
      sed -i .bak 's/hw.lcd.width=.*/hw.lcd.width=1080/' "$emulator_config"
      # Or, add new config
      if ! grep -q "hw.lcd.density" "$emulator_config"; then
        echo "hw.lcd.density=420" >> "$emulator_config"
      fi
      if ! grep -q "hw.lcd.height" "$emulator_config"; then
        echo "hw.lcd.height=1920" >> "$emulator_config"
      fi
      if ! grep -q "hw.lcd.width" "$emulator_config"; then
        echo "hw.lcd.width=1080" >> "$emulator_config"
      fi
      echo "Emulator settings ($emulator_config)"
      cat "$emulator_config"
      
      echo "Starting emulator and waiting for boot to complete..."
      nohup $ANDROID_HOME/emulator/emulator -avd android_emulator -no-snapshot -no-window -no-audio -no-boot-anim -camera-back none -camera-front none -qemu -m 2048 > /dev/null 2>&1 &
      $ANDROID_HOME/platform-tools/adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed | tr -d '\r') ]]; do sleep 1; done; input keyevent 82'
      echo "Emulator has finished booting"
      $ANDROID_HOME/platform-tools/adb devices
    displayName: 'Create and start emulator'
    condition: and(eq(variables['Build.SourceBranchName'], '${{ parameters.branchName }}'), eq(variables['Build.Reason'], '${{ parameters.buildReason }}'))


```

The error which I get from the build pipeline log is as shown below:

```
Generating script.
========================== Starting Command Output ===========================
/bin/bash /Users/runner/work/_temp/35648960-a4d4-4715-99d0-c9fd570ffd49.sh
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 5 more
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 5 more

##[error]Bash exited with code '1'.
Finishing: Download and install emulator image

```

Please help me in resolving this issue. 

Also Note: that I had also tried the approach mentioned on the link: https://learn.microsoft.com/en-us/azure/devops/pipelines/ecosystems/android?view=azure-devops#test-on-the-android-emulator

Still it gives the same error response.

**Comment by juliakm** [comment]
@Avi29071991 I've been talking to our support team about a similar-sounding issue for customers that use the Gradle@3 task. Can you please report the problem you've run into to support (if you haven't already) or to the [Azure DevOps developer community that is actively monitored by the product team](https://developercommunity.visualstudio.com/AzureDevOps)? I'm closing this issue but will work with the support team if there are related documentation updates to make.
